name: No Bass

on:
  workflow_dispatch:

jobs:
  process-audio:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Demucs and Dependencies
        run: |
          python -m pip install --upgrade pip
          # FIX: Install numpy secara eksplisit karena demucs butuh ini tapi tidak selalu ke-install otomatis
          pip install numpy
          # FIX: Install torchcodec secara manual karena torchaudio membutuhkannya
          pip install torch torchaudio torchcodec --index-url https://download.pytorch.org/whl/cpu
          pip install demucs

      - name: Create Directories
        run: |
          mkdir -p uploads
          mkdir -p output

      - name: Run Script
        run: python main.py

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "bass-result-${{ github.run_number }}"
          name: "Bass Audio Result #${{ github.run_number }}"
          body: "File audio ini berisi track tanpa bass"
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
